[files]
extend-exclude = [
  "*.json",
  "*.css",
  "*.svg",
  ".quarto/*",
  "_site/*",
  "_book/*",
  "_extensions/*",
  "*.bib",
]

[default.extend-words]
# Don't correct the misspelling of `interntal` in CHANGELOG
# and the raw data script.
interntal = "interntal"
